### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by newellp88** [louiefb/machine-learning-capstone-project#1]
## Rubric Score
 
### Criteria 1: Valid Python Code
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code runs without errors.
 
### Criteria 2: Exploration of Data
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Data is thoroughly explored with some unique methods of circumventing Pandas limitations on conditions. Using `df[‘column name’] = np.where(condition, value, column)` could have replaced a few of the for loops though. Still, a lot of attention was paid to minimize data loss and ensure features would support the study.
 
### Criteria 3: Machine Learning Techniques Used Correctly
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ 100% of the required model types were used and used correctly. Strong usage of scoring techniques, normalization and feature selection.
 
### Criteria 4: Report: Are conclusions clear and supported by data?
* _Score Level:_ 4 (Meets Expectations)
* _Comment(s):_ Results of the study were inconclusive, but the report addresses the potential causes and remedies for this in detail. 

### Criteria 5: Code Formatting
* _Score Level:_4 (Exceeds Expectations)
* _Comment(s):_ Code is clean, easily readable, and well documented.
 
### Overall Score: 20/20
Wow, excellent job! Your report is clean, professional, and showcases a strong understanding of Python and the modules used in this course. The code is clean, the questions match the enquiries into the data, conclusions really highlight your understanding of the results. I look forward to seeing any future research projects you might pursue.

**Comment by louiefb** [comment]
Thank you for the feedback
